version: "3.5"

services:
  cloud-storage:
    image: cloud-storage:latest
    ports:
    - 8000:8000
    networks:
    - djangonet
  postgresql:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "django"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
    ports:
      - "5432:5432"
    networks:
    - djangonet

networks:
  djangonet:
    driver: bridge
