# Generated by Django 5.0 on 2024-01-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('owner', models.CharField(max_length=40)),
            ],
        ),
    ]
